[project]
name = "servicebus"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
]
